import { ErrorState } from "@/components/ui/feedback";
import { OrderStatusBadge, TestOrderBadge } from "@/components/ui/status-badge";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { requireCustomer } from "@/lib/auth/user";
import { formatPrice } from "@/lib/data/product-options";
export const metadata: Metadata = { title: "My Orders" };
export default async function OrdersPage() { const { user, supabase } = await requireCustomer("/account/orders"); const { data, error } = await supabase.from("orders").select("id, order_number, created_at, total_amount, payment_method, status, is_test").eq("customer_id", user.id).order("created_at", { ascending: false }); if (error) return <ErrorState href="/account/orders">We couldn’t load your orders. Please retry.</ErrorState>; const orders = data ?? []; return <section><p className="account-eyebrow">Order history</p><h2>MY ORDERS</h2>{orders.length === 0 ? <div className="account-empty"><h3>NO ORDERS YET</h3><p>You haven&apos;t placed any orders yet.</p><Link href="/shop">Shop Cases <ArrowRight aria-hidden="true" /></Link></div> : <div className="orders-list">{orders.map((order) => <article key={order.id}><div><span>{new Intl.DateTimeFormat("en-EG", { dateStyle: "medium" }).format(new Date(order.created_at))}</span><h3><Link href={`/account/orders/${order.id}`}>{order.order_number}</Link></h3>{order.is_test ? <TestOrderBadge/> : null}</div><dl><div><dt>Status</dt><dd><OrderStatusBadge status={order.status}/></dd></div><div><dt>Payment</dt><dd>{order.payment_method.replaceAll("_", " ")}</dd></div><div><dt>Total</dt><dd>{formatPrice(order.total_amount)}</dd></div></dl><Link href={`/account/orders/${order.id}`} aria-label={`View ${order.order_number}`}>View <ArrowRight aria-hidden="true" /></Link></article>)}</div>}</section>; }
