'use server';

import { revalidatePath } from 'next/cache';
import { getStaffProfile } from '@/lib/admin/user';
import { requirePermission } from '@/lib/admin/permissions';
import { createAdminClient } from '@/lib/supabase/server';
import { namedCaseTemplateInputSchema } from '@/lib/custom-cases/templates';
import { processUploadImage } from '@/lib/images/process-upload';

async function requireProducts(permission: 'products.view'|'products.manage') { const staff=await getStaffProfile(); if(!requirePermission(staff,permission)) throw new Error(`Unauthorized: missing ${permission}`); return staff; }
const MIME:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif'}; const MAX=5*1024*1024;
function magic(b:Uint8Array,t:string){if(t==='image/png')return b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47;if(t==='image/jpeg')return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(t==='image/webp')return b[0]===0x52&&b[1]===0x49&&b[8]===0x57&&b[9]===0x45&&b[10]===0x42&&b[11]===0x50;if(t==='image/avif')return b[4]===0x66&&b[5]===0x74&&b[6]===0x79&&b[7]===0x70;return false}
export async function fetchAdminCustomCaseTemplates(){await requireProducts('products.view');const {data,error}=await createAdminClient().from('custom_case_templates').select('*').order('sort_order').order('name');if(error)throw new Error(error.message);return data??[]}
export async function fetchAdminCustomCaseTemplate(id:string){await requireProducts('products.view');const {data,error}=await createAdminClient().from('custom_case_templates').select('*').eq('id',id).maybeSingle();if(error)throw new Error(error.message);return data}
export async function saveCustomCaseTemplate(id:string|null,input:unknown,formData?:FormData){try{const staff=await requireProducts('products.manage');const parsed=namedCaseTemplateInputSchema.safeParse(input);if(!parsed.success)return {error:parsed.error.issues[0]?.message??'Invalid template settings.'};const supabase=createAdminClient();let imagePath:string|undefined;const file=formData?.get('file');if(file instanceof File&&file.size){if(file.size>MAX)return {error:'Image exceeds the 5 MB limit.'};if(!MIME[file.type])return {error:'Use JPEG, PNG, WebP, or AVIF.'};const bytes=new Uint8Array(await file.arrayBuffer());if(!magic(bytes,file.type))return {error:'Image content does not match its declared type.'};let processed;try{processed=await processUploadImage(bytes,file.type,'product')}catch(error){console.error('[custom-case-template] image processing rejected upload:',error instanceof Error?error.message:error);return {error:'The template image is not a valid supported image.'}}imagePath=`custom-case-templates/${crypto.randomUUID()}.${processed.extension}`;const {error}=await supabase.storage.from('product-assets').upload(imagePath,processed.bytes,{contentType:processed.mimeType,upsert:false});if(error)return {error:`Upload failed: ${error.message}`}}
if(!id&&!imagePath)return {error:'Template image is required.'};const p=parsed.data;const row={name:p.name,slug:p.slug,is_active:p.isActive,sort_order:p.sortOrder,allowed_script:'BOTH',max_characters:p.englishMaxCharacters,font_key:p.englishFontKey,font_size:p.englishFontSize,font_weight:p.englishFontWeight,text_color:p.englishTextColor,text_x:p.englishTextX,text_y:p.englishTextY,text_rotation:p.englishTextRotation,text_align:p.englishTextAlign,text_transform:p.englishTextTransform,english_max_characters:p.englishMaxCharacters,english_font_key:p.englishFontKey,english_font_size:p.englishFontSize,english_font_weight:p.englishFontWeight,english_text_color:p.englishTextColor,english_text_x:p.englishTextX,english_text_y:p.englishTextY,english_text_rotation:p.englishTextRotation,english_text_align:p.englishTextAlign,english_text_transform:p.englishTextTransform,arabic_max_characters:p.arabicMaxCharacters,arabic_font_key:p.arabicFontKey,arabic_font_size:p.arabicFontSize,arabic_font_weight:p.arabicFontWeight,arabic_text_color:p.arabicTextColor,arabic_text_x:p.arabicTextX,arabic_text_y:p.arabicTextY,arabic_text_rotation:p.arabicTextRotation,arabic_text_align:p.arabicTextAlign};const result=id?await supabase.from('custom_case_templates').update({...row,...(imagePath?{image_path:imagePath}:{})}).eq('id',id).select('id').single():await supabase.from('custom_case_templates').insert({...row,image_path:imagePath!,created_by:staff!.userId}).select('id').single();const {data,error}=result;if(error){if(imagePath)await supabase.storage.from('product-assets').remove([imagePath]);return {error:error.code==='23505'?'That slug is already in use.':error.message}}revalidatePath('/admin/custom-cases');revalidatePath('/custom-cases/named');return {id:data.id}}catch(e){return {error:e instanceof Error?e.message:'Unexpected error.'}}}
export async function setCustomCaseTemplateActive(id:string,isActive:boolean){try{await requireProducts('products.manage');const {error}=await createAdminClient().from('custom_case_templates').update({is_active:isActive}).eq('id',id);if(error)return {error:error.message};revalidatePath('/admin/custom-cases');revalidatePath('/custom-cases/named');return {ok:true}}catch(e){return {error:e instanceof Error?e.message:'Unexpected error.'}}}
