'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { saveCustomCaseTemplate, setCustomCaseTemplateActive } from '@/app/admin/actions/custom-cases';
import { NamedCasePreview } from '@/components/custom-cases/named-case-preview';
import { FeedbackRegion } from '@/components/ui/feedback';
import { requirePermission } from '@/lib/admin/permissions';
import { namedCaseFonts, namedCaseFontKeys, namedCaseTransforms, productAssetUrl, type NamedCaseTemplate } from '@/lib/custom-cases/templates';
import { ActionLink, Empty, Field, PageHeading, Panel, Pill, Table, Toggle } from './admin-ui';
import { useAdmin } from './admin-provider';

export function CustomCaseTemplatesLive({ templates }: { templates: NamedCaseTemplate[] }) {
  const { staff } = useAdmin(); const can = requirePermission(staff, 'products.manage'); const router = useRouter();
  const [pending, setPending] = useState<string | null>(null); const [feedback, setFeedback] = useState(''); const [failed, setFailed] = useState(false);
  return <><PageHeading title="Custom Case Designs" description="Named-case templates with independent English and Arabic text layers." action={can ? <ActionLink href="/admin/custom-cases/new">Add Design</ActionLink> : undefined}/><FeedbackRegion tone={failed ? 'danger' : 'success'}>{feedback}</FeedbackRegion><Panel title={`${templates.length} designs`}>{templates.length ? <Table headings={['Design','English max','Arabic max','Order','Status','Actions']}>{templates.map((template) => <tr key={template.id}><td><Image className="ad-thumb" src={productAssetUrl(template.image_path)} alt="" width={40} height={50}/><Link href={`/admin/custom-cases/${template.id}`}><strong>{template.name}</strong><small>{template.slug}</small></Link></td><td>{template.english_max_characters}</td><td>{template.arabic_max_characters}</td><td>{template.sort_order}</td><td><Pill color={template.is_active ? 'green' : 'grey'}>{template.is_active ? 'Active' : 'Inactive'}</Pill></td><td><div className="ad-actions"><Link href={`/admin/custom-cases/${template.id}`}>{can ? 'Edit' : 'View'}</Link>{can ? <button type="button" className={template.is_active ? 'ad-danger' : ''} disabled={pending !== null} onClick={async () => { setPending(template.id); setFeedback(''); const result = await setCustomCaseTemplateActive(template.id, !template.is_active); setPending(null); if ('error' in result) { setFailed(true); setFeedback(result.error ?? 'Could not update design.'); } else { setFailed(false); setFeedback(template.is_active ? 'Design deactivated.' : 'Design activated.'); router.refresh(); } }}>{pending === template.id ? (template.is_active ? 'Deactivating…' : 'Activating…') : template.is_active ? 'Deactivate' : 'Activate'}</button> : null}</div></td></tr>)}</Table> : <Empty>No named designs yet. Add the first real design when its artwork is ready.</Empty>}</Panel></>;
}

export function CustomCaseTemplateEditorLive({ template }: { template: NamedCaseTemplate | null }) {
  const router = useRouter(); const { staff } = useAdmin(); const canEdit = requirePermission(staff, 'products.manage');
  const [v, setV] = useState({
    name: template?.name ?? '', slug: template?.slug ?? '', isActive: template?.is_active ?? true, sortOrder: template?.sort_order ?? 0,
    englishMaxCharacters: template?.english_max_characters ?? 18, englishFontKey: template?.english_font_key ?? 'INTER', englishFontSize: template?.english_font_size ?? 38, englishFontWeight: template?.english_font_weight ?? 600, englishTextColor: template?.english_text_color ?? '#111111', englishTextX: Number(template?.english_text_x ?? 50), englishTextY: Number(template?.english_text_y ?? 44), englishTextRotation: Number(template?.english_text_rotation ?? 0), englishTextAlign: template?.english_text_align ?? 'center', englishTextTransform: template?.english_text_transform ?? 'UPPERCASE',
    arabicMaxCharacters: template?.arabic_max_characters ?? 18, arabicFontKey: template?.arabic_font_key ?? 'TAHOMA', arabicFontSize: template?.arabic_font_size ?? 38, arabicFontWeight: template?.arabic_font_weight ?? 600, arabicTextColor: template?.arabic_text_color ?? '#111111', arabicTextX: Number(template?.arabic_text_x ?? 50), arabicTextY: Number(template?.arabic_text_y ?? 56), arabicTextRotation: Number(template?.arabic_text_rotation ?? 0), arabicTextAlign: template?.arabic_text_align ?? 'center',
  });
  const [file, setFile] = useState<File | null>(null); const [blob, setBlob] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => () => { if (blob) URL.revokeObjectURL(blob); }, [blob]);
  const image = blob || (template ? productAssetUrl(template.image_path) : '');
  const set = <K extends keyof typeof v>(key: K, value: (typeof v)[K]) => setV((previous) => ({ ...previous, [key]: value }));
  const englishStyle = { fontKey:v.englishFontKey,fontSize:v.englishFontSize,fontWeight:v.englishFontWeight,textColor:v.englishTextColor,textX:v.englishTextX,textY:v.englishTextY,textRotation:v.englishTextRotation,textAlign:v.englishTextAlign };
  const arabicStyle = { fontKey:v.arabicFontKey,fontSize:v.arabicFontSize,fontWeight:v.arabicFontWeight,textColor:v.arabicTextColor,textX:v.arabicTextX,textY:v.arabicTextY,textRotation:v.arabicTextRotation,textAlign:v.arabicTextAlign };
  async function submit() { setBusy(true); setMessage(''); const formData = new FormData(); if (file) formData.append('file', file); const result = await saveCustomCaseTemplate(template?.id ?? null, v, formData); setBusy(false); if ('error' in result) { setMessage(result.error ?? 'Could not save the design.'); return; } router.push('/admin/custom-cases'); router.refresh(); }
  const numberField = (label:string,key:keyof typeof v,min:number,max:number) => <Field label={label}><input type="number" min={min} max={max} value={Number(v[key])} onChange={(event)=>set(key,Number(event.target.value) as never)}/></Field>;
  return <><PageHeading title={template ? 'Edit Named Design' : 'New Named Design'} description="Configure the English and Arabic name layers independently."/><div className="ad-editor cc-template-editor"><Panel title="Template settings">{!canEdit ? <p>Read-only access. Design changes require manage permission.</p> : null}<fieldset disabled={!canEdit || busy}><div className="ad-form-grid"><Field label="Design name"><input value={v.name} onChange={(event)=>set('name',event.target.value)}/></Field><Field label="Slug"><input value={v.slug} onChange={(event)=>set('slug',event.target.value.toLowerCase())}/></Field></div><Field label={template ? 'Replace template image (optional)' : 'Template image'}><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event)=>{const next=event.target.files?.[0]??null;setFile(next);setBlob(next?URL.createObjectURL(next):'');}}/></Field>
  <fieldset className="cc-template-layer"><legend>ENGLISH NAME STYLE</legend><div className="ad-form-grid"><Field label="Font"><select value={v.englishFontKey} onChange={(event)=>set('englishFontKey',event.target.value as typeof v.englishFontKey)}>{namedCaseFontKeys.map((key)=><option key={key} value={key}>{namedCaseFonts[key].label}</option>)}</select></Field>{numberField('Maximum characters','englishMaxCharacters',1,40)}{numberField('Font size','englishFontSize',10,96)}{numberField('Font weight','englishFontWeight',300,900)}<Field label="Color"><input type="color" value={v.englishTextColor} onChange={(event)=>set('englishTextColor',event.target.value)}/></Field>{numberField('X position %','englishTextX',0,100)}{numberField('Y position %','englishTextY',0,100)}{numberField('Rotation','englishTextRotation',-45,45)}<Field label="Alignment"><select value={v.englishTextAlign} onChange={(event)=>set('englishTextAlign',event.target.value as typeof v.englishTextAlign)}><option>left</option><option>center</option><option>right</option></select></Field><Field label="Transform"><select value={v.englishTextTransform} onChange={(event)=>set('englishTextTransform',event.target.value as typeof v.englishTextTransform)}>{namedCaseTransforms.map((value)=><option key={value}>{value}</option>)}</select></Field></div></fieldset>
  <fieldset className="cc-template-layer"><legend>ARABIC NAME STYLE</legend><div className="ad-form-grid"><Field label="Arabic-capable font"><select value={v.arabicFontKey} onChange={(event)=>set('arabicFontKey',event.target.value as typeof v.arabicFontKey)}>{(['ARIAL','TAHOMA'] as const).map((key)=><option key={key} value={key}>{namedCaseFonts[key].label}</option>)}</select></Field>{numberField('Maximum characters','arabicMaxCharacters',1,40)}{numberField('Font size','arabicFontSize',10,96)}{numberField('Font weight','arabicFontWeight',300,900)}<Field label="Color"><input type="color" value={v.arabicTextColor} onChange={(event)=>set('arabicTextColor',event.target.value)}/></Field>{numberField('X position %','arabicTextX',0,100)}{numberField('Y position %','arabicTextY',0,100)}{numberField('Rotation','arabicTextRotation',-45,45)}<Field label="Alignment"><select value={v.arabicTextAlign} onChange={(event)=>set('arabicTextAlign',event.target.value as typeof v.arabicTextAlign)}><option>left</option><option>center</option><option>right</option></select></Field></div></fieldset>
  <div className="ad-form-grid">{numberField('Sort order','sortOrder',0,10000)}</div><Toggle label="Active on storefront" checked={v.isActive} onChange={(value)=>set('isActive',value)}/>{message?<p className="ad-error" role="alert">{message}</p>:null}<div className="ad-savebar"><Link href="/admin/custom-cases">Cancel</Link><button className="ad-primary" disabled={busy} onClick={submit}>{busy?'Saving…':'Save Design'}</button></div></fieldset></Panel><Panel title="Live preview">{image?<NamedCasePreview image={image} imageAlt="Template preview" englishText={v.englishTextTransform==='UPPERCASE'?'MAZEN':'Mazen'} arabicText="مازن" englishStyle={englishStyle} arabicStyle={arabicStyle}/>:<Empty>Choose an image to start the preview.</Empty>}</Panel></div></>;
}
