'use client';
import Image from 'next/image';
import { useState } from 'react';
import { materialIds, materialOptions } from '@/lib/data/product-options';
import { previewAdminImages } from '@/lib/admin/image-storage';
import type { AdminProductImage } from '@/lib/admin/types';
import { FileUploadField } from '@/components/ui/file-upload-field';
import { Confirm, Field } from './admin-ui';

export function ImageManager({ images, onChange }: { images: AdminProductImage[]; onChange: (images: AdminProductImage[]) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [remove, setRemove] = useState<string | null>(null);
  function move(index: number, to: number) { const next = [...images]; const [image] = next.splice(index, 1); next.splice(to, 0, image); onChange(next); }
  return <><FileUploadField label="Add images" guidance="PNG, JPEG or WebP · Up to 5 MB each · 12 images maximum" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} error={error || undefined} onChange={async e => { const files = Array.from(e.target.files || []); e.target.value = ''; if (!files.length) return; setError(''); if (files.length + images.length > 12) return setError('Use up to 12 images per product.'); setBusy(true); try { onChange([...images, ...await previewAdminImages(files)]); } catch (err) { setError(err instanceof Error ? err.message : 'Could not preview images.'); } finally { setBusy(false); } }} /><p>Local previews only. The first image is the cover.</p>{busy && <p role="status">Preparing previews…</p>}<div className="ad-image-grid">{images.map((image, i) => <article key={image.id}><div className="ad-image-preview"><Image src={image.src} alt={image.alt} fill sizes="220px" unoptimized={image.src.startsWith('data:')} /></div><strong>{i + 1} · {i === 0 ? 'Cover image' : 'Gallery image'}</strong><Field label={`Image ${i + 1} description`}><input value={image.alt} onChange={e => onChange(images.map(item => item.id === image.id ? { ...item, alt: e.target.value } : item))} /></Field><Field label={`Image ${i + 1} group`}><select value={image.group} onChange={e => onChange(images.map(item => item.id === image.id ? { ...item, group: e.target.value as AdminProductImage['group'] } : item))}><option>General Gallery</option>{materialIds.map(m => <option value={m} key={m}>{materialOptions[m].label}</option>)}</select></Field><div className="ad-actions"><button type="button" disabled={i === 0} onClick={() => move(i, 0)}>Set cover</button><button type="button" disabled={i === 0} aria-label={`Move image ${i + 1} earlier`} onClick={() => move(i, i - 1)}>Earlier</button><button type="button" disabled={i === images.length - 1} aria-label={`Move image ${i + 1} later`} onClick={() => move(i, i + 1)}>Later</button><button type="button" onClick={() => setRemove(image.id)}>Remove</button></div></article>)}</div>{remove && <Confirm title="Remove this image?" close={() => setRemove(null)} onConfirm={() => onChange(images.filter(i => i.id !== remove))} />}</>;
}
