'use client';
import { useState } from 'react';
import Link from 'next/link';
import { money } from '@/lib/admin/analytics';
import { useAdmin } from './admin-provider';
import { Field, Modal } from './admin-ui';

export function SendCoupon({ couponId = '', customerId = '', close }: { couponId?: string; customerId?: string; close: () => void }) {
  const { data, update } = useAdmin(); const initial = data.customers.find(c => c.id === customerId); const [selected, setSelected] = useState(customerId); const [email, setEmail] = useState(initial?.email || ''); const [name, setName] = useState(initial?.name || ''); const [coupon, setCoupon] = useState(couponId || data.coupons.find(c => c.active && !c.archived)?.id || ''); const [preview, setPreview] = useState(false); const [done, setDone] = useState(false); const c = data.coupons.find(c => c.id === coupon);
  return <Modal title="Send Coupon" close={close}><form onSubmit={e => { e.preventDefault(); setPreview(true); setDone(false); }}><Field label="Customer"><select value={selected} onChange={e => { const u = data.customers.find(c => c.id === e.target.value); setSelected(e.target.value); setEmail(u?.email || ''); setName(u?.name || ''); setPreview(false); setDone(false); }}><option value="">Enter recipient manually</option>{data.customers.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><div className="ad-form-grid"><Field label="Customer name"><input required value={name} onChange={e => { setName(e.target.value); setPreview(false); setDone(false); }} /></Field><Field label="Customer email"><input type="email" required value={email} onChange={e => { setEmail(e.target.value); setPreview(false); setDone(false); }} /></Field></div><Field label="Coupon"><select required value={coupon} onChange={e => { setCoupon(e.target.value); setPreview(false); setDone(false); }}><option value="">Choose a coupon</option>{data.coupons.filter(c => !c.archived && (!c.customerId || c.customerId === selected)).map(c => <option value={c.id} key={c.id}>{c.code}</option>)}</select></Field><div className="ad-actions"><button type="submit">Preview Email</button><Link href={`/admin/coupons/new${selected ? `?customer=${selected}` : ''}`} onClick={close}>Create a coupon</Link></div></form>{preview && c && <><div className="ad-email"><strong>Subject: A special Coolcase discount for you</strong><p>Hi {name},</p><p>We have a special offer for you from Coolcase.</p><p>Use coupon:<br /><strong>{c.code}</strong></p><p>Discount:<br />{c.type === 'Percentage' ? `${c.value}%` : money(c.value)} off eligible Coolcase products.</p>{c.minimum > 0 && <p>Minimum products subtotal: {money(c.minimum)}.</p>}{c.type === 'Percentage' && c.maximum > 0 && <p>Maximum discount: {money(c.maximum)}.</p>}<p>Enter the code at checkout {c.expiry ? `before ${c.expiry}` : 'before it expires'}.</p><p>{data.settings.sender}</p></div><button className="ad-primary" disabled={done} onClick={() => { setDone(true); update(`Prepared coupon ${c.code} email preview (not sent).`, d => ({ ...d, emailPreviews: [...d.emailPreviews, { customerId: selected, couponId: coupon, date: new Date().toISOString() }] })); }}>Send Coupon</button></>}{done && <p className="ad-notice" role="status">Email sending will be connected to Gmail in the backend phase. No email was sent.</p>}</Modal>;
}
