'use client';
import { useState } from 'react';
import { orderStatuses, type AdminStoreSettings } from '@/lib/admin/types';
import { money } from '@/lib/admin/analytics';
import { useAdmin } from './admin-provider';
import { Field, PageHeading, Panel, Toggle } from './admin-ui';
import { Activity } from './dashboard';

export function Shipping() {
  const { data, update } = useAdmin(); const [fee, setFee] = useState(data.shipping.flatFee);
  return <><PageHeading title="Shipping" description="One simple shipping fee for every order." /><Panel title="Flat shipping"><form className="ad-narrow-form" onSubmit={e => { e.preventDefault(); const previous = data.shipping.flatFee; update(`Changed demo shipping from ${money(previous)} to ${money(fee)}.`, d => ({ ...d, shipping: { flatFee: fee } })); }}><Field label="Flat Shipping Fee (EGP)"><input type="number" required min="0" step="1" value={fee} onChange={e => setFee(+e.target.value)} /></Field><p>This shipping fee applies to all customer orders.</p><p>Changes here affect demo configuration only. Customer shipping remains 50 EGP until backend integration.</p><button className="ad-primary" type="submit">Save Changes</button></form></Panel><Panel title="Future configuration"><p>Zone-based shipping can be added later. Flat shipping is the current configuration.</p></Panel></>;
}
export function Settings() {
  const { data, update } = useAdmin(); const [settings, setSettings] = useState({ ...data.settings }); const [error, setError] = useState('');
  function set<K extends keyof AdminStoreSettings>(key: K, value: AdminStoreSettings[K]) { setSettings(s => ({ ...s, [key]: value })); }
  return <><PageHeading title="Settings" description="Store contact details and commerce preferences." /><form onSubmit={e => { e.preventDefault(); if (!settings.cod && !settings.instapay) return setError('Enable at least one payment method.'); setError(''); update('Updated store settings.', d => ({ ...d, settings })); }}><div className="ad-two"><Panel title="Store"><Field label="Store name"><input required value={settings.name} onChange={e => set('name', e.target.value)} /></Field><Field label="Support email"><input type="email" required value={settings.email} onChange={e => set('email', e.target.value)} /></Field><Field label="Support phone"><input type="tel" required pattern="01[0125][0-9]{8}" value={settings.phone} onChange={e => set('phone', e.target.value)} /></Field><Field label="WhatsApp"><input type="tel" required pattern="01[0125][0-9]{8}" value={settings.whatsapp} onChange={e => set('whatsapp', e.target.value)} /></Field></Panel><div className="ad-stack"><Panel title="Checkout"><Toggle label="COD enabled" checked={settings.cod} onChange={v => set('cod', v)} /><Toggle label="InstaPay enabled" checked={settings.instapay} onChange={v => set('instapay', v)} /><Field label="InstaPay number"><input type="tel" required pattern="01[0125][0-9]{8}" value={settings.instapayNumber} onChange={e => set('instapayNumber', e.target.value)} /></Field></Panel><Panel title="Orders"><Field label="Default order status"><select value={settings.defaultStatus} onChange={e => set('defaultStatus', e.target.value as AdminStoreSettings['defaultStatus'])}>{orderStatuses.map(s => <option key={s}>{s}</option>)}</select></Field></Panel></div><Panel title="Email"><Field label="Sender name"><input required value={settings.sender} onChange={e => set('sender', e.target.value)} /></Field><details><summary>Coupon email template preview</summary><div className="ad-email"><strong>A special Coolcase discount for you</strong><p>Hi [Customer Name],</p><p>We have a special offer for you from Coolcase.</p><p>Use coupon: [Coupon Code]</p><p>Discount: [Discount information] off eligible Coolcase products.</p><p>Enter the code at checkout before it expires.</p><p>{settings.sender}</p></div></details><p>Fixed template. Gmail delivery will be connected in the backend phase.</p></Panel><Panel title="Role preparation"><dl className="ad-totals"><div><dt>Owner</dt><dd>Everything</dd></div><div><dt>Manager</dt><dd>Products, orders, customers, coupons, analytics</dd></div><div><dt>Order Staff</dt><dd>Orders only</dd></div></dl><p>Preview permissions demonstrate UI visibility. Real permissions must be checked on the server for every operation.</p></Panel></div>{error && <p role="alert" className="ad-error">{error}</p>}<div className="ad-savebar"><button className="ad-primary" type="submit">Save Changes</button></div></form><Activity /></>;
}
