-- Seed the one fixed named custom-case design used by the customer storefront.
-- Layout fields are authoritative; customers can change only the two names and colors.

insert into public.custom_case_templates (
  id,
  name,
  slug,
  image_path,
  is_active,
  sort_order,
  allowed_script,
  max_characters,
  font_key,
  font_size,
  font_weight,
  text_color,
  text_x,
  text_y,
  text_rotation,
  text_align,
  text_transform,
  english_max_characters,
  english_font_key,
  english_font_size,
  english_font_weight,
  english_text_color,
  english_text_x,
  english_text_y,
  english_text_rotation,
  english_text_align,
  english_text_transform,
  arabic_max_characters,
  arabic_font_key,
  arabic_font_size,
  arabic_font_weight,
  arabic_text_color,
  arabic_text_x,
  arabic_text_y,
  arabic_text_rotation,
  arabic_text_align
)
values (
  '9f625d2c-8433-4fcc-8daf-4c09c594108a',
  'Signature Named Case',
  'signature-named-case',
  'custom-case-templates/named-case-fixed-base.png',
  true,
  0,
  'BOTH',
  7,
  'TAHOMA',
  64,
  700,
  '#221B78',
  54,
  57,
  0,
  'center',
  'NONE',
  7,
  'ARIAL',
  96,
  900,
  '#9FC5F8',
  51.5,
  55,
  0,
  'center',
  'UPPERCASE',
  7,
  'TAHOMA',
  64,
  700,
  '#221B78',
  54,
  57,
  0,
  'center'
)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  image_path = excluded.image_path,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  english_max_characters = excluded.english_max_characters,
  english_font_key = excluded.english_font_key,
  english_font_size = excluded.english_font_size,
  english_font_weight = excluded.english_font_weight,
  english_text_color = excluded.english_text_color,
  english_text_x = excluded.english_text_x,
  english_text_y = excluded.english_text_y,
  english_text_rotation = excluded.english_text_rotation,
  english_text_align = excluded.english_text_align,
  english_text_transform = excluded.english_text_transform,
  arabic_max_characters = excluded.arabic_max_characters,
  arabic_font_key = excluded.arabic_font_key,
  arabic_font_size = excluded.arabic_font_size,
  arabic_font_weight = excluded.arabic_font_weight,
  arabic_text_color = excluded.arabic_text_color,
  arabic_text_x = excluded.arabic_text_x,
  arabic_text_y = excluded.arabic_text_y,
  arabic_text_rotation = excluded.arabic_text_rotation,
  arabic_text_align = excluded.arabic_text_align;
